quick and dirty fix

diff --git a/iptables-banlist/banlist-deny-countries b/iptables-banlist/banlist-deny-countries
--- a/iptables-banlist/banlist-deny-countries
+++ b/iptables-banlist/banlist-deny-countries
@@ -1,30 +1,34 @@
-#!/bin/bash
+#!/bin/tcsh -f
 
 # LC = local
-ALLOWED=(LC GR CY)
-IPRCNT=/proc/net/xt_recent
+set ALLOWED = ( LC GR CY )
+set IPRCNT  = /proc/net/xt_recent
 
 #
-IPLIST=`cat $IPRCNT/CHECKIP | awk '/src=/ { print substr($1,5) }'`
-for IP in $IPLIST; do
-	geoinfo=$(geoiplookup "$IP" | head -n 1 | awk -F ": " '{print$2}')
-	if [[ $geoinfo =~ ^.*not\ found$ ]]; then
-		COUNTRY="LC"
+set IPLIST = `cat $IPRCNT/CHECKIP | awk '/src=/ { print substr($1,5) }'`
+foreach IP ( $IPLIST )
+	set geoinfo = `geoiplookup "$IP" | head -n 1 | awk -F ": " '{print$2}'`
+	echo $geoinfo | grep -i "IP Address not found" > /dev/null
+	if ( $status == 0 ) then
+		set COUNTRY = "LC"
 	else
-		COUNTRY=$(echo "$geoinfo" | awk -F "," '{ print $1 }')
-	fi
-	FOUND="0"
-	for CC in $ALLOWED; do
-		if [ "$CC" == "$COUNTRY" ]; then
-			FOUND="1"
+		set COUNTRY = `echo "$geoinfo" | awk -F "," '{ print $1 }'`
+	endif
+	unset found
+	foreach CC ( $ALLOWED )
+		if ( $CC == $COUNTRY ) then
+			set found
 			break
-		fi
-	done
-	if [ "$FOUND" == "0" ]; then
+		endif
+	end
+	if ( $?found ) then
+		unset found
+	else
 		logger -t "BANLIST" "Add $IP $geoinfo"
 		echo "+$IP" > $IPRCNT/BANLIST
 		echo "-$IP" > $IPRCNT/CHECKIP
-	fi
-done
+	endif
+end
+
 
 
